env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - airbnb
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules: {
  'indent': ["error", 4],
  'semi': 0, 'camelcase': 'off',
  'react/jsx-filename-extension': [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
  "react/jsx-indent" : ["error", 4],
  "import/extensions": 'off',
  "import/no-unresolved": 'off',
  "comma-dangle": 'off',
  'no-use-before-define': 'off',
  '@typescript-eslint/no-use-before-define': [ 'error' ],
#  'object-curly-newline': [ 'error', {
#    "ImportDeclaration": { "minProperties": 3, "consistent": false, "multiline": true },
#  } ],
  "react/jsx-indent-props": ["error", 4],
  "implicit-arrow-linebreak": 'off',
  "object-curly-newline": 'off',
  "no-confusing-arrow": 'off'
}

