env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - airbnb
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules: {
  'indent': ["error", 4],
  'semi': 0, 'camelcase': 'off',
  'react/jsx-filename-extension': [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
  "react/jsx-indent" : ["error", 4],
  "import/extensions": 'off',
  "import/no-unresolved": 'off'
}

